### PR TITLE
POSIX shell functions support

### LINKED ISSUE #1: POSIX-shell functions are not supported
ksh-style function definitions “function foo {}” are supported, but POSIX's "foo() {}” are not.
More on this here: [difference between “function foo() {}” and “foo() {}”](https://unix.stackexchange.com/questions/73750/difference-between-function-foo-and-foo)

The problem is addressed here:
[ [patch] POSIX shell functions support for Showing Current Function Name in Status Line (StlShowFunc) plugin ](https://groups.google.com/forum/#!topic/vim_dev/ZJVSrRShQb8)

I'll make PR later

@cecamp

### PR DESCRIPTION
**Pull request by bam80**
Fixes #1 
- add POSIX-style shell functions definition support:
    func_name () { ... }
- optimized function name search algorithm which runs _much_ faster
- overall cleanup

@ivanalejandro0 can you suggest someone who could review this?
@cecamp @mikeage

### CODE REVIEW

**Comment by ivanalejandro0** [comment]
> @ivanalejandro0 can you suggest someone who could review this?

Sorry, I don't know.
You could ask on a vim/neovim mailing list to see if anyone wants to take a look.

I don't think that this PR makes sense unless is approved by Dr Chip, though.
I think that a https://github.com/dr-chip-vim-scripts/plugin-name-here repo makes sense to hold within github the unmodified (and hopefully latest) version of the plugin, so it can be used by plugin managers for example.

I think that if you have changes that you need, you could have it on a personal fork that follows this particular repo... that way, you get to use your changes, and in the meantime all the repos on this org are mirroring the "official" code for the plugins.

Does that make sense?

**Comment by bam80** [comment]
@ivanalejandro0 if you don't mind, I would leave it as is for a while.
Let's see what Dr Chip reply, or what's the reaction of community.
For now, I don't see much sence to make such residual when there is no evidence of any demand for this repo, other than mine.

**Comment by mikeage** [comment]
Just out of curiosity, how did I get tagged here? I mean, I love vim, and I use it all the time as my editor and IDE, but I'm not particularly good with vimscript itself, and I don't think we've crossed paths before, unless I've just forgotten you, in which case I apologize...

That said, I think moving to git is an excellent idea; vimscripts and personal pages served their purposes in earlier days, but github is, hands down, the best platform for collaborative development, and anything that goes in that direction is to be encouraged.

**Comment by bam80** [comment]
> Just out of curiosity, how did I get tagged here?

https://github.com/search?q=StlShowFunc&type=Code :-)

@mikeage I just searching someone who use the plugin, to test the repo and this feature. And to get feedback.
Sorry if it disturbs you.

**Comment by mikeage** [comment]
No worries. I just wanted to make sure I wasn't missing something :-)

I'll give it a try. Looks like a good improvement.

**Comment by bam80** [comment]
@mikeage it's pleasant to hear for me :)

**Comment by ivanalejandro0** [comment]
> @ivanalejandro0 if you don't mind, I would leave it as is for a while.
Let's see what Dr Chip reply, or what's the reaction of community.
For now, I don't see much sence to make such residual when there is no evidence of any demand for this repo, other than mine.

Oh, sure... I don't mind this PR being open. I was just saying that if we add a change that is not on the upstream (http://www.drchip.org/astronaut/vim/index.html#STLSHOWFUNC), this plugin will no longer be "Dr Chip's plugin", but a plugin based on his plugin. Which is not a bad thing per-se, I just had something else in mind. People looking for the actual plugin may not want to use a modified version.

I think that we are good as long as we are clear enough of what this plugins is, original or modified.

@bam80 I'm not a user of this plugin, so feel free to make the calls about what's best for the repo yourself :) ... I wanted to share some thoughts in case it was useful.

**Comment by bam80** [comment]
> feel free to make the calls about what's best for the repo yourself

@ivanalejandro0 thanks for that. To be honest, I would rather merge the PR, just wanted to get any feedback beforehand. This PR just fixes old rudiment in the original and maybe abandoned code (~10 years old). It's hard to imagine if someone would be against the actual modified version.
About the name, I have mentioned in README it is "the community edtion". Maybe I should emphasize it better. I'm not sure if we can leave original "StlShowFunc" name for that. I think we should just follow the license. I didn't read it :)

**Comment by bam80** [comment]
Seems we got Dr Chip reply. He replied to the [vim_use@googlegroups.com group](https://groups.google.com/d/msg/vim_use/0Q-j8SNzRSQ/LEVAxRnJHAAJ):

> I'll look it over -- but I've got to finish getting my new windows box working (ie. recovery from corrupted backups due to a failing motherboard) followed by releasing a new&upgraded netrw.
>
> Chip

**Comment by ivanalejandro0** [comment]
closing this before archiving repo, see https://github.com/dr-chip-vim-scripts/StlShowFunc/issues/5

**Pull request closed without merging**
